spring.application.name=ms-pagamentos

spring.profiles.active=test
spring.jpa.open-in-view=false

eureka.client.register-with-eureka=true
eureca.client.fetch-registery=true

server.port=0

eureka.instance.instance-id=${spring.application.name}:${random.in[1,99]}